name: Setup
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2

    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        registry-url: https://registry.npmjs.org
        cache: pnpm

    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt
    
    - name: Install Cross
      run: cargo install cross --git https://github.com/cross-rs/cross
      shell: bash

    - name: pnpm install node modules
      run: pnpm i --frozen-lockfile
      shell: bash