[package]
name = "toml-parser"
version = "0.1.0"
edition = "2021"

[lib]
   crate-type = ["cdylib"]  # This is important for WebAssembly

[dependencies]
   wasm-bindgen = "0.2"  # For WebAssembly bindings
   toml = "0.5"
   serde = { version = "1.0", features = ["derive"] }
   serde_json = "1.0"
