version: 2.1

orbs:
  nx: nrwl/nx@1.6.2
  node: circleci/node@6.3.0
  utils: ethereum-optimism/circleci-utils@dev:first


commands:
  setup:
    description: "Setup"
    steps:
      - checkout
      - node/install-pnpm:
          version: '9'
      - run:
          name: Install pnpm dependencies
          command: pnpm install
      - nx/set-shas
      - run:
          name: Build
          command: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD --target=build
  configure-npm:
    description: "Configure NPM"
    steps:
      - run:
          name: Set NPM Credentials
          command: pnpm config set //registry.npmjs.org/:_authToken $NPM_TOKEN


jobs:
  publish-snapshots:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - setup
      - configure-npm
      - run: pnpm changesets-circle publish-snapshots

  lint:
    executor:
      name: node/default
      tag: '22.10'
    steps:
      - setup
      - run:
          name: Lint
          command: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD --target=lint
  test:
    executor:
      name: node/default
      tag: '22.10'
    steps:
      - setup
      - run:
          name: Unit Tests
          command: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD --target=test

  typecheck:
    executor:
      name: node/default
      tag: '22.10'
    steps:
      - setup
      - run:
          name: Typecheck
          command: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD --target=typecheck

  using-github-token:
    executor:
      name: node/default
      tag: '22.10'
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Print GitHub Token File Name
          command: |
            ls circleci-utils-github-token.secret.never.print

workflows:
  main:
    jobs:
      - lint
      - test
      - typecheck
  ci:
    jobs:
      - utils/set-github-token:
          context:
            - circleci-repo-super-cli
      - using-github-token:
          requires:
            - utils/set-github-token
