version: 2.1

orbs:
  nx: nrwl/nx@1.6.2
  node: circleci/node@6.3.0
  utils: ethereum-optimism/circleci-utils@1.0.16


commands:
  prepare-snapshot:
    description: "Prepare the snapshot name"
    steps:
      - run:
          name: Setup snapshot name
          command: |
            SNAPSHOT_NAME=${CIRCLE_BRANCH}
            echo "Will create snapshot using name $SNAPSHOT_NAME"
            echo "export SNAPSHOT_NAME=${SNAPSHOT_NAME}" >> "$BASH_ENV"
      - run:
          name: Prepare changeset version environment
          command: |
            echo "export GITHUB_TOKEN=${GITHUB_TOKEN_GOVERNANCE}" >> "$BASH_ENV"
      - run:
          name: Create snapshot versions
          command: pnpm release:version:snapshot

  setup:
    description: "Setup"
    steps:
      - checkout
      - node/install-pnpm:
          version: '9'
      - run:
          name: Install pnpm dependencies
          command: pnpm install --frozen-lockfile
          environment:
            NPM_TOKEN: nada

jobs:
  publish-to-npm:
    docker:
      - image: cimg/node:20.11
    parameters:
      prepare-snapshot:
        type: boolean
        default: false
    steps:
      - setup
      - run:
          name: Check NPM Token
          command: |
            if [ -z "${NPM_TOKEN}" ]; then
              echo "NPM_TOKEN is not set. Please set it in CircleCI project settings."
              exit 1
            fi

      - run:
          name: Configure NPM Token and Registry
          command: |
            npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"

      - run:
          name: Verify NPM Token
          command: npm whoami

      - run:
          name: Build
          command: pnpm nx run-many --target=build
          environment:
            NPM_TOKEN: nada

      - when:
          condition:
            equal: [<< parameters.prepare-snapshot >>, true]
          steps:
            - prepare-snapshot

      - utils/changesets:
          createGithubReleases: false
          publish: "pnpm release:publish"
          version: "pnpm release:version"


  check:
    executor:
      name: node/default
      tag: '22.10'
    steps:
      - setup
      - nx/set-shas
      - run:
          name: Build
          command: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD --target=build
      - run:
          name: Lint
          command: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD --target=lint
      - run:
          name: Unit Tests
          command: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD --target=test
      - run:
          name: Typecheck
          command: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD --target=typecheck

workflows:
  check-workflow:
    jobs:
      - check:
          filters:
            branches:
              ignore: main # ignore main branch as it is included in the release workflow
  release-workflow:
    jobs:
      - check
      - publish-to-npm:
          name: Publish new versions
          context:
            - circleci-repo-super-cli # for GITHUB_TOKEN_GOVERNANCE && NPM_TOKEN
          requires:
            - check
          filters:
            branches:
              only: main

      - publish-to-npm:
          name: Publish snapshot versions
          prepare-snapshot: true
          context:
              - circleci-repo-super-cli # for GITHUB_TOKEN_GOVERNANCE && NPM_TOKEN
          requires:
            - check
          filters:
            branches:
              only: main
