version: 2.1

orbs:
  utils: ethereum-optimism/circleci-utils@1.0.17
  nx: nrwl/nx@1.6.2



commands:
  prepare-snapshot:
    description: "Prepare the snapshot name"
    steps:
      - run:
          name: Setup snapshot name
          command: |
            SNAPSHOT_NAME=${CIRCLE_BRANCH}
            echo "Will create snapshot using name $SNAPSHOT_NAME"
            echo "export SNAPSHOT_NAME=${SNAPSHOT_NAME}" >> "$BASH_ENV"
      - run:
          name: Prepare changeset version environment
          command: |
            echo "export GITHUB_TOKEN=${GITHUB_TOKEN_GOVERNANCE}" >> "$BASH_ENV"
      - run:
          name: Create snapshot versions
          command: pnpm release:version:snapshot

  setup:
    description: "Setup Node.js environment with pnpm and nx"
    steps:
      - utils/checkout-with-mise      # Install dependencies
      - run:
          name: Install dependencies
          environment:
            NPM_TOKEN: nada
          command: |
            pnpm i --frozen-lockfile

jobs:
  publish-to-npm:
    machine:
      image: ubuntu-2204:2024.08.1
    parameters:
      prepare-snapshot:
        type: boolean
        default: false
    steps:
      - setup
      - run:
          name: Check NPM Token
          command: |
            if [ -z "${NPM_TOKEN}" ]; then
              echo "NPM_TOKEN is not set. Please set it in CircleCI project settings."
              exit 1
            fi

      - run:
          name: Configure NPM Token and Registry
          command: |
            npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"

      - run:
          name: Verify NPM Token
          command: npm whoami

      - run:
          name: Build
          command: pnpm nx run-many --target=build
          environment:
            NPM_TOKEN: nada

      - when:
          condition:
            equal: [<< parameters.prepare-snapshot >>, true]
          steps:
            - prepare-snapshot

      - utils/changesets:
          createGithubReleases: false
          publish: "pnpm release:publish"
          version: "pnpm release:version"


  check:
    machine:
      image: ubuntu-2204:2024.08.1
    steps:
      - setup
      - nx/set-shas
      - run:
          name: Build
          command: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD --target=build
      - run:
          name: Lint
          command: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD --target=lint
      - run:
          name: Unit Tests
          command: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD --target=test
      - run:
          name: Typecheck
          command: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD --target=typecheck

workflows:
  check-workflow:
    jobs:
      - check:
          filters:
            branches:
              ignore: main # ignore main branch as it is included in the release workflow
  release-workflow:
    jobs:
      - check:
          filters:
            branches:
              only: main
      - publish-to-npm:
          name: Publish new versions
          context:
            - circleci-repo-super-cli # for GITHUB_TOKEN_GOVERNANCE && NPM_TOKEN
          requires:
            - check
          filters:
            branches:
              only: main

      - publish-to-npm:
          name: Publish snapshot versions
          prepare-snapshot: true
          context:
              - circleci-repo-super-cli # for GITHUB_TOKEN_GOVERNANCE && NPM_TOKEN
          requires:
            - check
            - "Publish new versions"  # Changed from 'publish-to-npm' to the actual job name
          filters:
            branches:
              only: main
