[package]
name    = "toml-parser"
edition = "2021"
version = "0.0.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi        = "2"
napi-derive = "2"
serde_json = "1.0"
toml = "0.5"

[build-dependencies]
napi-build = "2"
