[package]
name    = "toml-parser"
edition = "2021"
version = "0.0.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi         = { workspace = true, default-features = false, features = ["napi3"] }
napi-derive  = { workspace = true }
serde_json = "1.0"
toml = "0.5"

[build-dependencies]
napi-build = { workspace = true }