name: Release snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - nick-test

jobs:
  build-node-bindings:
    name: Build node bindings
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build Node Bindings Artifacts
        run: ./scripts/release.sh
        shell: bash
      
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.sha }}-${{ matrix.os }}
          path: |
            packages/**/*.node
            !packages/**/node_modules
          retention-days: 1

  publish-snapshot:
    name: Publish snapshot release to npm
    if: github.repository == 'ethereum-optimism/super-cli'
    runs-on: ubuntu-latest
    needs: build-node-bindings
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Download Node Bindings Artifacts
        uses: actions/download-artifact@v4
        with:
          path: my-artifact
          pattern: build-artifacts-${{ github.sha }}-*
          merge-multiple: true

      - name: Copy Node Bindings Artifacts
        run: ./scripts/copy-artifacts.sh
        shell: bash

      - name: Set deployment token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Verify NPM Token is valid
        run: npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish snapshots
        uses: seek-oss/changesets-snapshot@v0
        with:
          pre-publish: pnpm nx run-many --target=build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}