name: Release snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - snapshots

jobs:
  publish-snapshot:
    name: Publish snapshot release to npm
    if: github.repository == 'ethereum-optimism/super-cli'
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup

      - name: Set deployment token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Verify NPM Token is valid
        run: npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish snapshots
        uses: seek-oss/changesets-snapshot@v0
        with:
          pre-publish: pnpm nx run-many --target=build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}