name: Release snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - snapshots

jobs:
  publish-snapshot:
    name: Publish snapshot release to npm
    if: github.repository == 'ethereum-optimism/super-cli'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: pnpm install node modules
        run: pnpm i --frozen-lockfile
        shell: bash

      - name: Set deployment token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Verify NPM Token is valid
        run: npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish snapshots
        uses: seek-oss/changesets-snapshot@v0
        with:
          pre-publish: pnpm nx run-many --target=build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}