name: Test node binding generation

on:
  workflow_dispatch:
  push:
    branches:
      - nick-test

jobs:
  build-artifacts:
    name: Build node bindings
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build Native Artifacts
        run: ./scripts/release.sh
        shell: bash
      
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.sha }}-${{ matrix.os }}
          path: packages/**/*.node
          retention-days: 1

  download-artifacts:
    needs: build-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: my-artifact
          pattern: build-artifacts-${{ github.sha }}-*
          merge-multiple: true
      - run: ls -R my-artifact
